Repository 2024-SummerBootcamp-Team-L/Frontend, pull requests merged in 2024-07, with the labels that each got.

#14 Onboarding Page1 Complete
  index.html
  src/components/MainPageButton.tsx
  src/pages/MainPage.tsx
  src/public/main_solomon.png
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
Labels: ✨ feat

#17 온보딩페이지1 화면비율 깨지는 것 수정
  src/pages/MainPage.tsx
Labels: 🔨 fix

#22 로그인 후 나오는 온보딩 페이지 퍼블리싱
  src/App.tsx
  src/components/MainPageBlackButton.tsx
  src/components/MainPageWhiteButton.tsx
  src/pages/MainPage.tsx
  src/pages/MainPage2.tsx
  tailwind.config.js
Labels: ✨ feat

#41 fix : Fixing result page css
  package-lock.json
  package.json
  src/components/ScrollableBox.tsx
  src/pages/ResultPage.tsx
  src/public/ResultBackground.png
Labels: 🔨 fix

#43 [chore] Frontend and Backend 폴더 합침
  src/pages/ResultPage.tsx
Labels: 🍎 chore

#47 [feat] 회원가입 api 연동 완료
  package-lock.json
  package.json
  src/pages/SignupPage.tsx
Labels: ✨ feat

#65 [fix] SignupPage.tsx 파일 타입 수정 완료
  src/pages/LoginPage.tsx
  src/pages/MainPage2.tsx
  src/pages/SignupPage.tsx
Labels: 🔨 fix

#76 [feat] 결과페이지 기능구현 완료
  src/App.tsx
  src/api.ts
  src/components/ScrollableBox.tsx
  src/pages/ResultPage.tsx
Labels: ✨ feat

#99 feat:로딩페이지 구현 완료
  package-lock.json
  package.json
  src/components/LoadingPage.tsx
  src/lottie/animation.json
  src/pages/CategoryPage.tsx
  src/pages/JudgePageCopy.tsx
  src/pages/JudgePageCopy2.tsx
  src/pages/LatestPostPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MyPostPage.tsx
  src/pages/ResultPage.tsx
  src/pages/SignupPage.tsx
  tsconfig.json
Labels: ✨ feat, 🎨 design

#117 [feat] 결과페이지 글자처리
  src/components/ScrollableBox.tsx
  src/pages/JudgePageCopy.tsx
  src/pages/ResultPage.tsx
  src/pages/ResultPage2.tsx
Labels: ✨ feat

#126 [faet]파비콘 설정 완료
  index.html
  src/public/favicon-32x32.png
Labels: ✨ feat, 🎨 design
